version: '3'

services:
  spring-backend:
    container_name: spring-backend-blue
    image: ghcr.io/kwongiyeon/5-team-daramgil-sumda-be:latest
    ports:
      - "8081:8080"
    env_file:
      - .env