services:
  be-blue:
    image: ghcr.io/kwongiyeon/5-team-daramgil-sumda-be:latest
    ports:
      - "8081:8080"
    env_file:
      - .env
    container_name: be-blue
    network_mode: bridge
    restart: always

  be-green:
    image: ghcr.io/kwongiyeon/5-team-daramgil-sumda-be:latest
    ports:
      - "8082:8080"
    env_file:
      - .env
    container_name: be-green
    network_mode: bridge
    restart: always