services:
  be-blue:
    image: ghcr.io/kwongiyeon/5-team-daramgil-sumda-be:latest
    platform: linux/amd64
    ports:
      - "8081:8080"
    env_file: .env
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AIR_PUBLIC_API_KEY: ${AIR_PUBLIC_API_KEY}
      WEATHER_PUBLIC_API_KEY: ${WEATHER_PUBLIC_API_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID}
      JWT_SECRET: ${JWT_SECRET}
    container_name: be-blue
    network_mode: bridge
    restart: always