version: '3'

services:
  spring-backend:
    container_name: spring-backend-green
    image: ghcr.io/100-hours-a-week/5-team-daramgil-sumda-be:latest
    ports:
      - "8082:8080"
    env_file:
      - .env