version: '3'

services:
  spring-backend:
    container_name: spring-backend-green
    image: kwongy/sumda-be:latest
    ports:
      - "8082:8080"
    env_file:
      - .env


#services:
#  be-green:
#    image: ghcr.io/kwongiyeon/sumda-be:latest
#    platform: linux/amd64
#    ports:
#      - "8082:8080"
#    env_file: .env
#    environment:
#      DB_URL: ${DB_URL}
#      DB_USERNAME: ${DB_USERNAME}
#      DB_PASSWORD: ${DB_PASSWORD}
#      OPENAI_API_KEY: ${OPENAI_API_KEY}
#      AIR_PUBLIC_API_KEY: ${AIR_PUBLIC_API_KEY}
#      WEATHER_PUBLIC_API_KEY: ${WEATHER_PUBLIC_API_KEY}
#      SENTRY_DSN: ${SENTRY_DSN}
#      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
#      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID}
#      JWT_SECRET: ${JWT_SECRET}
#    container_name: be-green
#    network_mode: bridge
#    restart: always