version: '3'

services:
  spring-backend:
    container_name: spring-backend-blue
    image: ghcr.io/100-hours-a-week/5-team-daramgil-sumda-be
    ports:
      - "8081:8080"
    env_file:
      - .env