spring:
  application:
    name: sumda
  profiles:
    active: local
    include: my

  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/sumda
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # ?? ????? ??, ??????? ??? ??
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: {your-client-id}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "https://localhost:3000/oauth"
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao