name: CI/CD with Docker

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_BACK_BLUE }} >> ~/.ssh/known_hosts

      - name: Verify SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_BACK_BLUE }} echo "SSH connection successful"

      - name: Send deploy.sh
        uses: 100-hours-a-week/5-team-daramgil-sumda-be@develop
        with:
          username: ubuntu
          host: ${{ secrets.EC2_BACK_BLUE }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: "./deploy.sh"
          target: "/home/ubuntu/"

      - name: Pull and deploy Docker image on EC2 (Blue or Green)
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_BACK_BLUE }} << 'EOF'
            # 현재 실행중인 컨테이너 색상 확인 (blue 또는 green)
            CURRENT_COLOR=$(docker ps --filter 'name=be-blue' --filter 'status=running' -q)

            if [ -z "$CURRENT_COLOR" ]; then
              echo "### BLUE => GREEN ###"
              # green 컨테이너를 실행하기 위해 최신 이미지를 가져옵니다.
              docker pull ghcr.io/kwongiyeon/5-team-daramgil-sumda-be:latest
              docker stop be-blue || true
              docker rm be-blue || true
              docker run -d -p 8081:8081 --name be-green --env-file /home/${{ secrets.EC2_USER }}/.env ghcr.io/kwongiyeon/5-team-daramgil-sumda-be:latest
          
              # Nginx 설정 변경 후 재시작
              sudo cp /etc/nginx/nginx.green.conf /etc/nginx/nginx.conf
              sudo nginx -s reload

            else
              echo "### GREEN => BLUE ###"
              # blue 컨테이너를 실행하기 위해 최신 이미지를 가져옵니다.
              docker pull ghcr.io/kwongiyeon/5-team-daramgil-sumda-be:latest
              docker stop be-green || true
              docker rm be-green || true
              docker run -d -p 8080:8080 --name be-blue --env-file /home/${{ secrets.EC2_USER }}/.env ghcr.io/kwongiyeon/5-team-daramgil-sumda-be:latest
          
              # Nginx 설정 변경 후 재시작
              sudo cp /etc/nginx/nginx.blue.conf /etc/nginx/nginx.conf
              sudo nginx -s reload
            fi
          EOF